# demo-api (HTTP API + Kafka Producer)
# Managed by Argo CD (App-of-Apps pattern)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # TODO: Tạo repo riêng cho demo-api sau
    repoURL: git@github.com:john-naeder/slsa-k8s-platform.git
    targetRevision: main
    path: code/src/demo-api/k8s   # Thư mục chứa deployment.yaml, service.yaml, ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
