---
# =============================================================================
# userver-home-worker — Host vars cho worker node
# =============================================================================

tailscale_ip: "100.94.203.28"
node_role: "worker"
