---
# =============================================================================
# userver-master — Host vars cho control plane node
# =============================================================================

tailscale_ip: "100.95.126.102"
node_role: "master"
